### ISSUE TITLE
GPT retrieval chart requires BEARER_TOKEN and OPENAI_API_KEY to be plain text

### ISSUE THREAD

**Issue by Kriska** [icoretech/helm#4]
Currently,
When I use the gpt-retrieval-plugin chart as a dependency:
```yaml
apiVersion: v2
name: my-deployment
type: application
version: 0.0.1
dependencies:
- name: chatgpt-retrieval-plugin
  alias: gptretrieval
  version: 0.0.18
  repository: https://icoretech.github.io/helm
  condition: gptretrieval.enabled

```
and I configure it in the values.yaml file:
```yaml
gptretrieval:
  enabled: true
  web:
    image: ghcr.io/icoretech/chatgpt-retrieval-plugin-docker:weaviate-e8fda70-1690594131
    extraEnvs:
      - name: DATASTORE
        value: weaviate
      - name: WEAVIATE_URL
        value: http://weaviate:80
      - name: BEARER_TOKEN
        value: blabla
      - name: OPENAI_API_KEY
        value: blabla
```
I need to provide the BEARER_TOKEN and OPENAI_API_KEY directly in plain text.

This exposes my configurations and although [they are later wrapped as a secret.](https://github.com/icoretech/helm/blob/main/charts/chatgpt-retrieval-plugin/templates/web-env-secret.yaml)
They are also present as a plain text in my values file.

It would be much more useful if either:
- users can configure [the secret GPT retrieval plugin needs ](https://github.com/icoretech/helm/blob/main/charts/chatgpt-retrieval-plugin/templates/web-deployment.yaml#L41)
- users can pass extraEnvFromSecret and [it is considered by the default secret](https://github.com/icoretech/helm/blob/main/charts/chatgpt-retrieval-plugin/templates/web-env-secret.yaml#L8)
